export enum KeyboardButtons {
    Shift = 'Shift',
    Escape = 'Escape',
    Backspace = 'Backspace',
    Line = 'l',
    Rectangle = '1',
    Pencil = 'c',
    Ellipse = '2',
    Eraser = 'e',
    Aerosol = 'a',
    InvalidInput = 'h',
    NewDrawing = '0',
    Up = 'ArrowUp',
    Down = 'ArrowDown',
    Left = 'ArrowLeft',
    Right = 'ArrowRight',
    Export = 'e',
    Save = 's',
    Carousel = 'g',
    Polygon = '3',
}
