export enum TextFont {
    Arial = 'Arial',
    ArialBlack = 'Arial Black',
    ArialNarrow = 'Arial Narrow',
    Calibri = 'Calibri',
    Candara = 'Candara',
    ComicSansMS = 'Comic Sans MS',
    Consolas = 'Consolas',
    Courier = 'Courier',
    CourierNew = 'Courier New',
    Georgia = 'Georgia',
    Helvetica = 'Helvetica',
    Impact = 'Impact',
    LucidaConsole = 'Lucida Console',
    SegoeUI = 'Segoe UI',
    Tahoma = 'Tahoma',
    TimesNewRoman = 'Times New Roman',
    TrebuchetMS = 'Trebuchet MS',
    Verdana = 'Verdana',
}
