export enum ToolsNames {
    Pencil = 'Pencil',
    Eraser = 'Eraser',
    Rectangle = 'Rectangle',
    Ellipse = 'Ellipse',
    Line = 'Line',
    Aerosol = 'Aerosol',
    Pipette = 'Pipette',
    Polygon = 'Polygon',
    Text = 'Text',
    PaintBucket = 'PaintBucket',
    Stamp = 'Stamp',
    SelectBox = 'SelectBox',
    SelectEllipse = 'SelectEllipse',
    SelectPolygon = 'SelectPolygon',
    Magnetism = 'Magnetism',
}
